name: Matter Controller
on: push
jobs:
  build:
    runs-on: debian-latest
    steps:
      - run: sudo apt update
      - run: > 
         sudo apt install git gcc g++ pkg-config cmake curl libssl-dev libdbus-1-dev 
         libglib2.0-dev libavahi-client-dev ninja-build python3-venv python3-dev 
         python3-pip unzip libgirepository1.0-dev libcairo2-dev libreadline-dev 
         libevent-dev default-jre
      - run: sudo apt install -y git
      - run: git clone --depth=1 git@github.com:project-chip/connectedhomeip.git
      - run: cd connectedhomeip
      - run: ./scripts/checkout_submodules.py --shallow --platform  linux
