name: Firmware for nrf52840 dongle
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: sudo apt update
      - run: sudo apt install -y python3-pip git cmake ninja-build
      - run: pip3 install --user -U west --break-system-packages
      - run: curl https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil -o nrfutil
      - run: chmod +x nrfutil
      - run: echo $PATH
      - run: sudo mv nrfutil /usr/local/bin/
      - run: nrfutil install device
      - run: nrfutil install nrf5sdk-tools
      - run: nrfutil install toolchain-manager
      - run: nrfutil toolchain-manager search
      - run: nrfutil toolchain-manager install --ncs-version v2.9.1
      - run: mkdir -p nrfbuild
      - run: cd nrfbuild
      - run: python3 -m west init -m https://github.com/nrfconnect/sdk-nrf --mr main
      - run: python3 -m west update
      - run: python3 -m west zephyr-export
      - run: cd nrf/samples/openthread/coprocessor
      - run: nrfutil toolchain-manager launch # --shell
      # - run: west build -b nrf52840dongle/nrf52840 -p
      # - run: nrfutil pkg generate --hw-version 52 --sd-req=0x00 --application build/merged.hex --application-version 1 otbr-rcp.zip
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: blob
          path: foo