name: Open Thread Border Router
on: push
jobs:
  build:
    runs-on: debian-latest
    env:
      BACKBONE_ROUTER: 1
      BORDER_ROUTING: 1
      NAT64: 0
      DNS64: 0
      DHCPV6_PD: 0
      DHCPV6_PD_REF: 0
      WEB_GUI: 1
      REST_API: 1
      INFRA_IF_NAME: eth0
    steps:
      - run: sudo apt update
      - run: sudo apt install -y git
      - run: git clone https://github.com/openthread/ot-br-posix.git --depth 1
      - run: cd ot-br-posix
    #  - run: export BACKBONE_ROUTER=1
    #  - run: export BORDER_ROUTING=1
    #  - run: export NAT64=0
    #  - run: export DNS64=0
    #  - run: export DHCPV6_PD=0
    #  - run: export DHCPV6_PD_REF=0
    #  - run: export WEB_GUI=1
    #  - run: export REST_API=1
    #  - run: export INFRA_IF_NAME=eth0
      - run: ./script/bootstrap
      - run: ./script/setup